### ISSUE TITLE
Double entries

### ISSUE THREAD

**Issue by pedrorissi81** [oklona/Miele-MQTT#10]
Hi,

With the actual version I got the following behaviour:

_miele_000xxxxxxx13_000xxxxxxx13_000xxxxxxx13_Time Left | 00:01 | 04/09/2020 11:03:40 AM
-- | -- | --
_miele_000xxxxxxx13_000xxxxxxx13_000xxxxxxx13_Time Running | 00:00 | 04/09/2020 11:03:40 AM
_miele_000xxxxxxx13_000xxxxxxx13_000xxxxxxx13_Vent ilationStep | '' | 04/09/2020 11:03:40 AM
_miele_000xxxxxxx13_000xxxxxxx13_ApplianceType | 'Dishwasher' | 04/09/2020 11:03:07 AM
_miele_000xxxxxxx13_000xxxxxxx13_DryingStep | '' | 04/09/2020 11:03:07 AM
_miele_000xxxxxxx13_000xxxxxxx13_ProgramPhase | 'Unknown: 0' | 04/09/2020 11:03:07 AM
_miele_000xxxxxxx13_000xxxxxxx13_ProgramStatus | 'Off' | 04/09/2020 11:03:07 AM
_miele_000xxxxxxx13_000xxxxxxx13_ProgramType | '0' | 04/09/2020 11:03:07 AM
_miele_000xxxxxxx13_000xxxxxxx13_TimeLeft | 00:01 | 04/09/2020 11:03:07 AM
_miele_000xxxxxxx13_000xxxxxxx13_TimeRunning | 00:00 | 04/09/2020 11:03:07 AM
_miele_000xxxxxxx13_000xxxxxxx13_VentilationStep | '' | 04/09/2020 11:03:07 AM
_miele_000xxxxxxx13_ApplianceType | 'Dishwasher' | 04/09/2020 11:02:34 AM
_miele_000xxxxxxx13_DryingStep | '' | 04/09/2020 11:02:34 AM
_miele_000xxxxxxx13_LightON | '2' | 04/09/2020 11:02:34 AM
_miele_000xxxxxxx13_ProgramPhase | 'Unknown: 0' | 04/09/2020 11:02:34 AM
_miele_000xxxxxxx13_ProgramStatus | 'Off' | 04/09/2020 11:02:34 AM
_miele_000xxxxxxx13_ProgramType | '0' | 04/09/2020 11:02:34 AM
_miele_000xxxxxxx13_TimeLeft | 00:01 | 04/09/2020 11:02:34 AM
_miele_000xxxxxxx13_TimeRunning | 00:00 | 04/09/2020 11:02:34 AM
_miele_000xxxxxxx13_VentilationStep | '' | 04/09/2020 11:02:34 AM
loxberry_mqttgateway_keepaliveepoch | 1586423854 | 04/09/2020 11:17:34 AM
loxberry_mqttgateway_status

After a few minutes the script stops

**Comment by oklona** [comment]
Hello. This newest version of the script is meant to run in the background, and poll and publish data every 30 seconds. -So the behavior seen here is correct, except it shouldn't quit after a few minutes.

The reason for this change, is that people were requesting the ability to send commands to the Miele appliances. In order for these commands to be picked up by something, the script obviously needed to stay alive.

To run it just once and quit (like it worked previously), pass the parameter "-s" (single run).

**Comment by oklona** [comment]
Sorry, just tested it myself, and now I see what you mean! The hardware ID of the appliance is added to the string for each single run! Somehow funny, but not really :-) Will fix!

**Comment by oklona** [comment]
If you could please verify that this has fixed your problem, I would be grateful if you report back, so I can close this issue :-)

**Comment by pedrorissi81** [comment]
It works like expected. No doubled entries anymore:

`

Miniserver Virtual Input | Last value | Last submission
-- | -- | --
_miele_0xxxxxxxxxxxxx3_ApplianceType | 'Dishwasher' | 04/14/2020 1:03:05 PM
_miele_0xxxxxxxxxxxxx3_DryingStep | '' | 04/14/2020 1:03:05 PM
_miele_0xxxxxxxxxxxxx3_LightON | '2' | 04/14/2020 1:03:05 PM
_miele_0xxxxxxxxxxxxx3_ProgramPhase | 1802 | 04/14/2020 1:03:05 PM
_miele_0xxxxxxxxxxxxx3_ProgramStatus | 0 | 04/14/2020 1:03:05 PM
_miele_0xxxxxxxxxxxxx3_ProgramType | '0' | 04/14/2020 1:03:05 PM
_miele_0xxxxxxxxxxxxx3_TimeLeft | 00:01 | 04/14/2020 1:03:05 PM
_miele_0xxxxxxxxxxxxx3_TimeRunning | 00:00 | 04/14/2020 1:03:05 PM
_miele_0xxxxxxxxxxxxx3_VentilationStep | '' | 04/14/2020 1:03:05 PM
loxberry_mqttgateway_keepaliveepoch | 1586862179 | 04/14/2020 1:02:59 PM

`
