### ISSUE TITLE
phpMQTT.php link in miele-MQTT.php

### ISSUE THREAD

**Issue by pedrorissi81** [oklona/Miele-MQTT#12]
On my loxberry I got this error when starting the script
`
PHP Fatal error:  Uncaught Error: Class 'phpMQTT' not found in /opt/loxberry/webfrontend/legacy/miele/miele-MQTT.php:284
Stack trace:
#0 {main}
  thrown in /opt/loxberry/webfrontend/legacy/miele/miele-MQTT.php on line 284
Fatal error: Uncaught Error: Class 'phpMQTT' not found in /opt/loxberry/webfrontend/legacy/miele/miele-MQTT.php:284
Stack trace:
#0 {main}
  thrown in /opt/loxberry/webfrontend/legacy/miele/miele-MQTT.php on line 284
`

so changing from
`$mqtt = new phpMQTT($mosquitto_host, "1883", $client_id);`
to
`$mqtt = new Bluerhinos\phpMQTT($mosquitto_host, "1883", $client_id);`
fixes the problem

maybe this can be adapted, too?

regards
Pedro

**Comment by oklona** [comment]
Yes, of course! Sorry for that, I had discovered that, but thought it was just a mistake in my local code...

**Comment by pedrorissi81** [comment]
looks great!
