### ISSUE TITLE
only a question about the openhab-thread

### ISSUE THREAD

**Issue by AleksCee** [oklona/Miele-MQTT#14]
Hi,

I found the [openHab](https://community.openhab.org/t/miele-cloud-binding/93266) thread and hope you also work on this Script ahead? Because I use it to publish the API-Output via MQTT to nodeRED.

THX, Alex

**Comment by oklona** [comment]
Hello. Yes, for now, I still use this script in my environment, and try to keep it up to date :-)

**Comment by AleksCee** [comment]
Can you explain what the openHab "new way" looks like? Is this an option for nodeRED also?

**Comment by oklona** [comment]
Yeah, in OpenHAB, Miele themselves are writing an OpenHAB-specific binding for Miele appliances, using the API. Obviously, this makes it a fully supported solution, and makes my script obsolete for my use-case, which is specifically OpenHAB.
