### ISSUE TITLE
Addition of PUT actions

### ISSUE THREAD

**Issue by ChutneyMary** [oklona/Miele-MQTT#2]
**Miele have advised with effect 19 September -**

19 September 2018
Maintenance release of Miele 3rd party API (OpenBeta)

Current version is V1.0.1

Changes

- added CORS Support for for inline answers within the API documentation.
- added OAUTH2 via Client Credentials Flow
- added PUT actions route for simple control of devices

**Is there a possibility to incorporate PUT actions through MQTT?**

**Comment by alealdata** [comment]
Registration to the broker with user and password

**Comment by oklona** [comment]
Hmm... Yes, that should be possible. I need to look through the updates to the API :-)

**Comment by oklona** [comment]
Need to rewrite much of the script for this to work, as the script now would need to be left running, to listen for incoming commands. This could naturally be a separate script, derived from the first one, using the same config-file. -Or it could be the same script, that could take a parameter to be in "listen" mode.

**Comment by ChutneyMary** [comment]
Is there scope to decide what input format will be used to receive incoming commands? I assume MQTT would be obvious...but if there's scope to use POST commands, that would also work for many home automation systems.

**Comment by ChutneyMary** [comment]
Hi oklona. Any progress with PUT actions for the API?

**Comment by oklona** [comment]
Hello. I will be looking at this now. As mentioned, I will need to rewrite quite a bit, as the script is currently single-threaded, without any looping. Now it will need to be running "permanently" to listen for incoming actions, and then execute the querying of devices regularly.

**Comment by ChutneyMary** [comment]
I forward the following information from Miele. This suggests new credentials are required to continue using the API

"Dear users of the Miele 3rd Party API, 

Today ends the beta phase of the Miele 3rd Party API. Tomorrow we will officially release version 1.0 of the API. We would like to thank all participants of the beta-phase and thank you for the received feedback. Not all requests and suggestions could be directly considered, but we promise to make changes and improvements all the time and are always happy to receive your feedback and suggestions (which are included in our backlog). 

What's new (changes)? 
First, we have adjusted our terms of use. This was necessary for commercial users to use the API.
We also made small adjustments to individual endpoints, for example SpinningSpeed ​​is now localized. 
We have also increased the number of possible actions. Before an action is executed on a device, a GET action can be used to check which actions are available. 

What's next? 
We will change the registration process. This new procedure eliminates the need to request credentials by e-mail. Customer ID and customer password can be created directly on developer.miele.com. 
However, this change requires all API users to create new credentials. The old credentials expire 30 days after the launch date of the new registration.
We will inform you shortly by e-mail about the date of the change. 

Thanks again for participating in the beta program. 

Best regards, 
Your Miele 3rd Party API Team"

**Comment by oklona** [comment]
Yes, I saw that. However, as they say, the old credentials expire 30 days after they make it possible to get new credentials. -So the old ones will still work for at least a month.

For incorporating actions, I have a few options: 
- To keep using parts of the current script, but have a loop that checks for incoming MQTT messages (and acts on the incoming messages) every second or so, and polls data from Miele every 30-60 seconds.
- To use a PHP MQTT library, which will simplify the programming, but make the installation procedure more cumbersome, as users will need to install PHP extensions that may be difficult to install on some platforms.
- To rewrite everything, using python, which has a good MQTT library, or even write it in C++. Using C++ would again probably require users to compile the code and stuff, which makes it more difficult to start using for some.

As of now, I lean towards the first option, as that will probably be the fastest way to get something ready, and it could still be contained within one script.

**Comment by christianTF** [comment]
Hi, I‘m Christian, the developer of the MQTT->Loxone Gateway.

Some of my plugin’s users use your Miele script to talk to the MQTT broker.

For my users, currently I prefer option 1.

Regarding PHP: 
The best implemented PHP Lib mosquitto-php needs mosquitto-devel installed, and configured in php.ini (not nice).
I have https://github.com/techdada/phpMQTT (forked from https://github.com/bluerhinos/phpMQTT) in my watchlist, but not tried yet. It php-natively implements the mqtt protocol.

Python would be comparable easily to install, but C no novice user might get managed.

Regards, Christian

**Comment by oklona** [comment]
Agreed, so at least for now, that is the path I will be following.

**Comment by oklona** [comment]
I have now made some updates, and implemented the bluerhinos stack into the script. It is now possible to send commands to the appliances. In order to verify responses from the Miele API after posting your commands, you can uncomment the var_dump statement in line 289.

Since the script now needs to listen for MQTT data, it runs continuously, and checks data from Miele every 30 seconds.

I am considering adding an oAuth token refresh every week, or something like that, by adding a timestamp for the token into the config file, and trigger a refresh based upon that.

I am also considering command switches for just running once, publish data, and exit (will naturally make issuing commands impossible), and also possibly a switch to trigger json output, as someone requested this through another channel.
